# Generated by Django 3.2.7 on 2021-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfl_profile',
            name='profile_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Profile name'),
        ),
    ]
