# Generated by Django 3.2.7 on 2021-09-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cntnt_comments',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Comments')),
                ('like_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inside_comment', to='content.cntnt_comments')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'cntnt_comment',
            },
        ),
        migrations.CreateModel(
            name='cntnt_status',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(verbose_name='Status')),
                ('is_current_profile_status', models.BooleanField(default=False)),
                ('like_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_uploaded_status', to='profiles.prfl_profile')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuss',
                'db_table': 'cntnt_status',
            },
        ),
        migrations.CreateModel(
            name='cntnt_picture',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('picture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='profile_pic/')),
                ('is_current_profile_picture', models.BooleanField(default=False)),
                ('like_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_uploaded_picture', to='profiles.prfl_profile')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'db_table': 'cntnt_picture',
            },
        ),
        migrations.CreateModel(
            name='cntnt_likes',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_on_comment', to='content.cntnt_comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_by', to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_on_picture', to='content.cntnt_picture')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_on_status', to='content.cntnt_status')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'cntnt_like',
            },
        ),
        migrations.AddField(
            model_name='cntnt_comments',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_picture', to='content.cntnt_picture'),
        ),
        migrations.AddField(
            model_name='cntnt_comments',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_status', to='content.cntnt_status'),
        ),
    ]
