# Generated by Django 3.2.7 on 2021-09-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cntnt_status',
            name='is_current_profile_status',
        ),
    ]
