# Generated by Django 3.2.7 on 2021-09-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frnd_friends_mapping',
            fields=[
                ('mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('friends_id', models.ManyToManyField(blank=True, related_name='friends_mapping_with_profile', to='profiles.prfl_profile')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_friends_mapping', to='profiles.prfl_profile')),
            ],
            options={
                'verbose_name': 'Friend mapping',
                'verbose_name_plural': 'Friends mapping',
                'db_table': 'frnd_friends_mapping',
            },
        ),
    ]
